### ISSUE TITLE
DPM-Solver Memory Problem

### ISSUE THREAD

**Issue by lin-tianyu** [WuJunde/MedSegDiff#23]
Hi! Thanks for your excellent work. I successfully trained a MedSegDiff-B model on my dataset but have trouble sampling.

Specifically, **while using DPM-Solver to sample, the memory usage of GPU improves with the 'num_ensemble' parameter.** In every ensemble model(1/5), the GPU memory improves around 2GB and finally collapses with the "CUDA out of memory" error.

This problem allows me to sample only one image before the inference process collapses. Is this a normal phenomenon? If not, how can I deal with it?

PS: using the original inference process can sample images without increasing GPU memory.

**Comment by WuJunde** [comment]
no, it did not happen in my workplace. You must modified sth in the code. Each ensemble should be individual, you may want to release the memory every time after the sampling.

**Comment by lin-tianyu** [comment]
After a little debugging, I discovered that each time [https://github.com/WuJunde/MedSegDiff/blob/master/guided_diffusion/dpm_solver.py](dpm_solver.py) line 1193 is executed, the GPU memory increase. (Still don't know why 🧐but whatever)

**Luckily, the problem was solved after I changed my Pytorch version from _1.10.0_ to _1.8.1_**. Thanks for your help!

**Comment by WuJunde** [comment]
wow, thanks for your valuable information. I will try to reproduce and fix it. Anyway, congrats on solving the problem.

**Comment by jaceqin** [comment]
> Hi! Thanks for your excellent work. I successfully trained a MedSegDiff-B model on my dataset but have trouble sampling.
> 
> Specifically, **while using DPM-Solver to sample, the memory usage of GPU improves with the 'num_ensemble' parameter.** In every ensemble model(1/5), the GPU memory improves around 2GB and finally collapses with the "CUDA out of memory" error.
> 
> This problem allows me to sample only one image before the inference process collapses. Is this a normal phenomenon? If not, how can I deal with it?
> 
> PS: using the original inference process can sample images without increasing GPU memory.

After I change the version of Pytorch, I still add 2GB of video memory each time. Do you have any other modifications?

**Comment by TheWangYang** [comment]
I have solved the same problem just change the pytorch's version from 1.10.0 to 1.8.1(cuda 10.2). Thanks alot for this issue.
